name: Action Test

on: [push, pull_request]

jobs:
  git-cliff-action:
    runs-on: ubuntu-latest
    name: Test the git-cliff changelog generator action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        id: git-cliff
        uses: ./
        with:
          config: fixtures/cliff.toml
          args: >
            --verbose
            --strip 'footer'
            --exclude-path '.github/**'
            --tag 0.0.0
            --with-commit "\'test(changelog): add a custom commit\'"
        env:
          OUTPUT: fixtures/CHANGELOG.md
      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
      - name: Print the version
        run: echo "${{ steps.git-cliff.outputs.version }}"
