name: Action Test

on: [ push, pull_request ]

jobs:
  git-cliff-action:
    runs-on: ubuntu-latest
    name: Test the git-cliff changelog generator action
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "."
      - name: Generate a changelog
        id: git-cliff
        uses: ./
        with:
          config: fixtures/cliff.toml
          args: --verbose --strip 'footer' --exclude-path '.github/**' --tag 0.0.0
        env:
          OUTPUT: fixtures/CHANGELOG.md
      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
      - name: Print the version
        run: echo "${{ steps.git-cliff.outputs.version }}"
